### ISSUE TITLE
Multiple traits to create a service

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1061]
Both the `container` trait and the `service` trait allow to configure a service. Does anyone recall why?
Can we rationalize it?

@jamesnetherton , @astefanutti

**Comment by astefanutti** [comment]
It's coming from 45d5666e699460da51051874fd918dfe82399300. The intent was about getting the Prometheus trait aware of the service trait. But it leaked into the container trait and the Prometheus trait had to be fixed in 64553ae05309806ebbdf999179a3edc4bcc425ee anyway.

I agree it's still confusing and can likely be improved.

**Comment by lburgazzoli** [comment]
The original "design" was to have the service trait as master and other traits to customize the service created by the `servce` trait.

**Comment by lburgazzoli** [comment]
I think now we have a single point where the service is created an other traits can amend it so, can we close this on @nicolaferraro ?
