### ISSUE TITLE
Adding camel-jackson dependency creates issues with inner classes 

### ISSUE THREAD

**Issue by mmistretta** [apache/camel-k#1507]
When adding the camel-jackson dependency, comments with imports, actual imports, etc inner classes are no longer found. 

version: Camel K Client and Operator 1.0.0-RC2
Example: https://github.com/jeremyrdavis/quarkus-cafe-demo/commits/camel-k-addition
      - commit works: d95b5ea360ca1dabe333b2ce568fc87b18e8594d
      - commit does not work: 4ee524f4ccf2c9dce3005b80e7fa44b4d1546528

Process on OpenShift 4.4:
- Create project
- Install camel k operator
- kamel install --olm=false --skip-cluster-setup --skip-operator-setup --maven-repository  https://jitpack.io@id=jitpack@snapshots
- kamel run --name=rest-with-undertow --dependency=camel-rest --dependency=camel-undertow --dependency=mvn:com.github.jeremyrdavis:quarkus-cafe-demo:1.2-SNAPSHOT RestWithUndertow.java

**Comment by lburgazzoli** [comment]
This should not be an issue any-more in camel-k 1.0.0 ?

The issues was caused by a bug in the jOOR library which is used to compile the Java integration at runtime which is included in jOOR's 0.9.13 [1]. The camel-k-runtime version used by camel-k RC2 is 
1.1.0 [2] which dos not includes the fix [3]

[1] https://github.com/jOOQ/jOOR/issues/99
[2] https://github.com/apache/camel-k/blob/1.0.0-RC2/script/Makefile#L19
[3] https://github.com/apache/camel-k-runtime/blob/camel-k-runtime-parent-1.1.0/pom.xml#L42

@mmistretta can you please confirm ?

**Comment by mmistretta** [comment]
i used this commit: https://github.com/jeremyrdavis/quarkus-cafe-demo/commit/5e8c7c47f7082a68e2c30dd7adcea0cad4bce56e
and still get Caused by: java.lang.ClassNotFoundException: RestWithUndertow.GrubHubOrder

**Comment by lburgazzoli** [comment]
@mmistretta I've finally been able to find the root cause, here the related issues:

- https://issues.apache.org/jira/browse/CAMEL-15199
- https://github.com/apache/camel-k-runtime/issues/364

**Comment by lburgazzoli** [comment]
I think we can close this now that we have all the pieces released
