### ISSUE TITLE
jib builder

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1656]
Evaluate to use jib [1] as a builder strategy and eventually leverage its plug-in extension mechanism [2]

[1] https://github.com/GoogleContainerTools/jib
[2] https://cloud.google.com/blog/products/application-development/using-jib-to-containerize-java-apps

**Comment by lburgazzoli** [comment]
I think it would be nice to consolidate on jib (except of s2i probably) and get rid of the other build strategies mentioned here: https://github.com/apache/camel-k/issues/3336

**Comment by squakez** [comment]
Would it make sense to target for a 2.0 version? It looks like we won't be able to maintain compatibility (at least, not that easily) if we switch to something new.

**Comment by lburgazzoli** [comment]
Yes for 2.x

**Comment by squakez** [comment]
Something else we want to consider is to support multi-architecture via JIB: see #1238

**Comment by gansheer** [comment]
I spent some time getting to know the existing JIB plugins available. 

The ones I found and tested are:
* [Quarkus Container Extension Jib](https://quarkus.io/guides/container-image) (camel-k quarkus version) 
* [Jkube Kubernetes Plugin](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin/) (version 1.10.1)
* [Jib maven plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin) (version 3.3.1)
* [Fabric8 docker plugin](https://dmp.fabric8.io/) (version 0.41.0)

I did some build test using the following requirements :
* build a container image containing the content from the /tmp/kit-xxxxxx-yyyyy/context instead of the default target folder ( /tmp/kit-xxxxxx-yyyyy/maven/target)
* build incrementally the container images between multiple integration kits by having some influence on layer build
* build the container image for different architectures (linux/am64, linux/arm64, etc)
* producing a container image the most 

The native build still needs to be tested but in the context of container image build is it also about a runner being made available in /tmp/kit-xxxxxx-yyyyy/context after the build phase, so it should be covered but the requirements.

I put all my data here : https://github.com/gansheer/jib-work

**Only two of the tested plugins validate all the requirements** : **Jib maven plugin** and **Fabric8 docker plugin**. Seeing the **Fabric8 docker plugin**'s version is 0.41.0, I feel the **Jib maven plugin** is the best choice.

The **Jkube Kubernetes Plugin** is still a good candidate if it can add the multi-architecture support. I found it offers a lot of flexibility and also come with an Jkube Openshift Plugin built on top of Kubernetes Plugin that has s2i features.

What I see as an implementation roadmap for the addition of a jib publish strategy would be:
* implement a first version using the **Jib maven plugin** while discussing with the jkube projet to see if the multi-architecture can be added 
* if (and hopefully when) the **Jkube Kubernetes Plugin** provides the multi-architecure feature, plan a migration to the JKuve plugin

Last notes:
* Java native build still need to be tested, particularly [the java native build PR](https://github.com/apache/camel-k/pull/4021).  
* I didn't see anything incompatible with [the build decoupling discussions](https://github.com/apache/camel-k/issues/3831)

Please don't hesitate to tell me your opinions on this and any additional inputs.

cc @lburgazzoli @astefanutti @oscerd @claudio4j @christophd @tadayosi

**Comment by squakez** [comment]
Great analysis. I think that eventually JIB and JKube may coexist if we manage to have enough resources to support both. For the time being we could start with JIB implementation IMO.

**Comment by gansheer** [comment]
Thank for you input @squakez .

To explain the technical code problem. The maven command expect the following informations:
* GlobalSettings: KO computed by BuildTask
* UserSettings: KO computed by BuildTask
* SettingsSecurity: KO computed by BuildTask
* ExtraMavenOpts: KO computed by BuildTask (mainly Truststore) 
* LocalRepository: OK since available from ip through `localRepository` 
* AdditionalArguments : Partially available from ip through `cliOptions` 
* AdditionalEntries: can't see any code using this one.

https://github.com/apache/camel-k/blob/4b5b5d313268b9171b9bd9ae72e16ab49c392676/pkg/util/maven/maven_command.go#L157-L166

Just to be clear : your advice is to only take what is in the /tmps/kit-xxxxxx directory by principle and ignore what is computed in the build task ?

**Comment by squakez** [comment]
So, what you're trying to do is to unmarshal what the "build" has provided before. IMO we could avoid that step and instead change the configuration structure on the directory files. Basically it would be a very low level "publisher" whose goal is to parse the pom xml, add some configuration with some raw editor, save it back and run the `mvn compile` accordingly.

**Comment by squakez** [comment]
Closed by https://github.com/apache/camel-k/pull/4680
