### ISSUE TITLE
runtime : create cloudevents camel component

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#171]
We should create a component that support events according to the [cloudevents](https://cloudevents.io/) specifications

**Comment by lburgazzoli** [comment]
Once ready the component should be moved to camel upstream

**Comment by nicolaferraro** [comment]
Looking at the transport spec: https://github.com/cloudevents/spec/blob/v0.1/http-transport-binding.md

Cloudevents supports a request/reply pattern, so we can use it also to "invoke" a remote route e.g. from a function.

We can rely on cloudevents instead of creating a propretary transport for the "lightweight camel client". Wdyt?

**Comment by lburgazzoli** [comment]
+1

**Comment by oscerd** [comment]
Good idea!
