### ISSUE TITLE
Using -SNAPSHOT prevents rebuilding past commits

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#1878]
I am currently trying to trace down an error and I am hitting an interesting problem.

I am trying to figure out which commit introduced the error but since past commits explicitly use the 1.6.0-SNAPSHOT (which doesn't exist anymore), this prevents me from actually rebuilding older versions of camel-k.

It would be good to avoid the direct use of versions which contain the SNAPSHOT tag in them. I'm not sure I have a solution for how to avoid that but one thing is for sure, whatever the name, we must ensure that the package exists under maven even after the SNAPSHOT tag has moved to a new version.

**Comment by nicolaferraro** [comment]
Yeah, from time to time we need to switch to SNAPSHOT to refer to the runtime artifacts. I've added to the local run comands the `--maven-repository` option so that it's possible to reference `https://repository.apache.org/content/repositories/snapshots` even in `kamel local run`, and it contains the snapshot artifacts, compiled from the runtime master.

Unfortunately, we can't publish on maven central unreleased bits automatically, because we need to start a vote on Apache and let the community tests artifacts for 72 hours before releasing anything on Maven. So we opted on using SNAPSHOTs, usually for short period of times, to sync operator and runtime and move both forward.

**Comment by johnpoth** [comment]
@nicolaferraro is there an easy way to run an integration using locally built SNAPSHOTs of camel-k-runtime ?

**Comment by nicolaferraro** [comment]
> @nicolaferraro is there an easy way to run an integration using locally built SNAPSHOTs of camel-k-runtime ?

Local run uses local maven, so I guess it will pick your compiled version. It wouldn't work with the released version, but if you build a `kamel` with runtime-version set to x.x.x-SNAPSHOT in the Makefile (plus `make codegen` before `make`), then `kamel local run` will pick your local runtime.

**Comment by johnpoth** [comment]
Thanks @nicolaferraro! I was thinking of running it in Kubernetes but maybe running it locally will be enough, thanks!

**Comment by doru1004** [comment]
I guess my question is, is it needed to go through a phase where -SNAPSHOT is used?

Instead of using 1.6.0-SNAPSHOT, one could advance the SNAPSHOT tag of the other project to something like 1.6.1-SNAPSHOT thus leaving 1.6.0 to not have a SNAPSHOT tag. Then Camel-K will have no mention of SNAPSHOT in its source code. If we then need to use the latest 1.6.1-SNAPSHOT, we first move the SNAPSHOT to 1.6.2-SNAPSHOT and then use 1.6.1 in Camel-K and so on.
