### ISSUE TITLE
Creating Ingress and services with Kubernetes 

### ISSUE THREAD

**Issue by kasun04** [apache/camel-k#189]
Hi @nicolaferraro ,
I'm running Kamel on Docker for Mac + Kubernetes. 

I've deployed a sample integration examples/routes-rest.js and was expecting it to create svc, ingress etc so that I can invoke my RESTful service.  (As you mentioned in : "So, for example, if you define a REST endpoint using the Camel REST DSL, the operator will make sure that your integration is exposed to the outside and it will create a Service and a Route on OpenShift to expose it, or a Ingress on vanilla Kubernetes." [1] ) 

However, I don't see that the Kamel operator create svc or ingress.
Do I have to manually create ingress, service etc for that? Here are the pod and svc information. 

kubectl get pods
NAME                                READY     STATUS    RESTARTS   AGE
camel-k-operator-64c5686848-4zkzt   1/1       Running   0          2h

./kamel get
NAME		CONTEXT	STATUS
routes
routes-rest

kubectl get svc
NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
camel-k-operator   ClusterIP   10.97.6.139   <none>        60000/TCP   2h
kubernetes         ClusterIP   10.96.0.1     <none>        443/TCP     3h

[1] https://www.nicolaferraro.me/2018/10/15/introducing-camel-k/

**Comment by nicolaferraro** [comment]
Hi @kasun04, Camel K needs a docker registry to push images to. That's why for local development it's better to use Minikube, because you can install a default registry through a Minikube addon.
Is a docker registry present in your dev-env?

Also, can you inspect the status of the platform objects?

```
kubectl get integrationplatform -o yaml
kubectl get integrationcontext -o yaml
kubectl get integration -o yaml
```

I suspect that the platform is not "Ready" because it cannot push the context images.
