### ISSUE TITLE
Warnings on getting operator versions

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1930]
I see these messages in CI:

```
Could not parse <nil> (error: Invalid Semantic Version)
Warning: you're using Camel K 1.4.0-SNAPSHOT client against a  cluster operator
```

Something related to the operator version check? @astefanutti , @squakez

**Comment by squakez** [comment]
Most likely yes. The way it works, every "online" command try to get the cluster operator version. It matches against the client, and if major.minor differs return the warning.

**Comment by squakez** [comment]
I managed to replicate the issue locally. I am not sure how the `e2e` tests are working but the operator that is installed is failing:
```
Error from server (BadRequest): container "camel-k-operator" in pod "camel-k-operator-7c5db4c5c9-799c8" is waiting to start: trying and failing to pull image
```
Neither there is an integration platform installed in the temporary namespace. Is that the expected behavior of the test procedure? if that is the case we may include a skip warning flag in order to avoid cluttering those tests.

**Comment by astefanutti** [comment]
A default IntegrationPlatform is created by the `kamel install` command. So the check is too early for that command, as the version status has not be reconciled yet :)

I think we can exclude the `install` command from the list of commands for which the check applies, as, while it is "online", it does not interact with the operator, since it has yet to be installed. Actually, as far as the check is concern, the right semantic should be "interacts with the operator", rather than "online".

Otherwise, we can skip the check when the `.status.version` field is `nil`.
