### ISSUE TITLE
cli: add a binding sub command

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2083]
We should have a kamel subcommand to create KameltBinding, something like:

```
kamelet bind --from=telegram-text-source --to=my-topic@kafka.strimzi.io/v1beta1:KafkaTopic 
```

Things to take into account:
- how to properly bind properties to a kamelet, when it is used multiple times

**Comment by lburgazzoli** [comment]
Thinking a little bit more, we can also add options to define intermediate steps, like:

```
kamelet bind 
	--from=telegram-text-source 
    --step=log-action
    --step=filter-action
    --to=my-topic@kafka.strimzi.io/v1beta1:KafkaTopic
```

**Comment by heiko-braun** [comment]
What about `--steps=[one,two, three, ...]` (ordered list)?

**Comment by heiko-braun** [comment]
Also, will we have `kamel rebind` at some point? Asking for a friend who wonders how updates to bindings are performed

**Comment by nicolaferraro** [comment]
So, the impl in #2183 does a redeploy by default in case of matching binding name (which is computed after the bound resources, or it can be passed as `--name` arg).
The CLI has a nice sintax for multiple steps that is like:

```
--step kamelet1 --step kamelet2
```

They are kept sorted. The problem is when `kamelet1` has a required parameter... how do we specify it?
