### ISSUE TITLE
Runtime reload configmap/secret when they change

### ISSUE THREAD

**Issue by makandre** [apache/camel-k#2106]
Opening this request to capture discussion here: https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/watching.20mounted.20configmap.2Fsecret

**Use case:**  When values in a mounted configmap/secret is changed (e.g. a password to a service), would like a way to reload at runtime without needing to restart the integration (pod)

**Comment by heiko-braun** [comment]
Considering that Camel K rebuilds are fast, would it be safer to trigger a rebuild & redeploy of the integration, rather than reloading the runtime? From the outset (i.e. user changing creds) it would appear similar (the runtime uses the new credentials), but internally, we would move through regular kubernetes lifecycle steps (rebuild, redeploy, rollover, readiness checks). Reloading at runtime doesn't sounds right to me.

**Comment by squakez** [comment]
Duplicates of #1235
