### ISSUE TITLE
build camel-k on windows

### ISSUE THREAD

**Issue by onderson** [apache/camel-k#213]
Platform : Windows 10

and mingw64 is also under use for such build.

>go version
go version go1.11.2 windows/amd64

dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : windows/amd64
 features    : ImportDuringSolve=false

>make --version
GNU Make 4.0
Built for i686-w64-mingw32
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

when i go to directory 

C:\dev\go-workspace\src\github.com\apache\camel-k

and run make dep

the output is.

Makefile:1: ***.  Stop.

This may not be related to camel-k directly, this is an issue to log in purporse of looking for a solution in windows builds.

PS: Searching through, i found that tabs vs spaces could be an issue but as per my attempts to try both failed.

**Comment by onderson** [comment]
@dmvolod , I took `make dep` as an example as it was documented. Just `make` also fails.

**Comment by nicolaferraro** [comment]
@onderson can you try to execute one step at time to understand where it hangs.
I'd start with:

```
go build -o camel-k ./cmd/camel-k/*.go
```

It corresponds to `make build-operator`, that should also work if it works.

**Comment by onderson** [comment]
fails on windows shell;
`C:\dev\go-workspace\src\github.com\apache\camel-k>go build -o camel-k ./cmd/camel-k/*.go
GetFileAttributesEx ./cmd/camel-k/*.go: The filename, directory name, or volume label syntax is incorrect.`

**Comment by orpiske** [comment]
The problem is that the `Makefile` is a symlink to `script/Makefile` (assuming that was the case at the time the ticket was opened). 

So, the build command for Windows should be `make -f script/Makefile`. However, there are other portability issues which would require fix. 

I have a patch that is able to partially build the project (only the `build-kamel` target). I don't intend to send this as contribution to the project (because I don't know enough about windows to do so and lack of interest), but it should give an idea of what is required for that in case anyone wants to contribute it: https://github.com/orpiske/camel-k/commit/15bd93c28a8b24aabfa84160cbef452988a8aecd
