### ISSUE TITLE
install: optional registry

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2358]
camel-k installation tries to determine a registry and may fail if it does not find one.
in some environment, camel-k is not supposed to perform any build so we should have an option to make the registry optional

**Comment by phantomjinx** [comment]
Current plan:

1. `kamel install` already contains a --registry switch so if this is set to `none` then the user can flag no registry
2. If o.Registry.Address == none then find the building trait in the catalog, copy, disable it then add it to the IntegrationPlatform
3. Try a `kamel run ...` (& write tests) to prove that a build cannot be attempted and the empty Registry{} never used

**Comment by phantomjinx** [comment]
Latest implementation carries through the `--registry none` and implements 3 changes:
- platform.Spec.Registry.Address = Disabled
- platform.Spec.BuildPublsihStrategy = Disabled
- platform.Spec.BuildStrategy = Disabled

This seemed logical since the registry is required for `BuildPublishStrategy` and since one of the active types of `BuildPublishStrategy` are required for `BuildStrategy`. If this is not correct then can you provide an example please?

If it is correct, can you provide a use-case where the operator is useful without any build capability, please? 

thx.

cc @lburgazzoli @astefanutti

**Comment by astefanutti** [comment]
> Latest implementation carries through the `--registry none` and implements 3 changes:
> 
> * platform.Spec.Registry.Address = Disabled
> * platform.Spec.BuildPublishStrategy = Disabled
> * platform.Spec.BuildStrategy = Disabled
> 
> This seemed logical since the registry is required for `BuildPublishStrategy` and since one of the active types of `BuildPublishStrategy` are required for `BuildStrategy`. If this is not correct then can you provide an example please?

That is correct.

> If it is correct, can you provide a use-case where the operator is useful without any build capability, please?

The use case it to run an Integration using a pre-built image. Obviously, this pre-built image has to comply with the Camel K runtime contract (that is not documented ;). As an easy way to write an e2e test for this, I think we could re-use any existing test, and add a subsequent test that would re-deploy the same Integration, by re-using the previously built image, and make sure both the operator installation and the Integration Pod run successfully.

**Comment by phantomjinx** [comment]
PR -> https://github.com/apache/camel-k/pull/2464

**Comment by phantomjinx** [comment]
*New* PR -> https://github.com/apache/camel-k/pull/2497

**Comment by astefanutti** [comment]
It's been fixed with #2497.
