### ISSUE TITLE
Let dependencies be defined using HTTP URLs

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#240]
We allow `mvn:` dependencies with `camel:` and `runtime:` wrapper. We should allow users to specify HTTP dependencies on libs (to load custom JAR that are not present in Maven central).

**Comment by squakez** [comment]
I am not sure if this is still relevant to these days, as the feature was requested already long time ago. If it's still the case, maybe we can think to upload the dependency on the operator local m2 via `[install-file](https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html)` just the first time we use it. Maybe we can generate some SHA in order to guarantee uniqueness starting from the URI that defines the dependency. The only concern I have is if it makes sense for the operator to host some dependency that could be malicious (altough the same could apply for any mvn dependency I guess).

**Comment by squakez** [comment]
Managed in https://github.com/apache/camel-k/issues/2834

**Comment by squakez** [comment]
I got confused. Now that we have local file dependency in place, we may turn this easily into a new feature that will leverage that development. Ie, we can let the CLI download the http located jar in a temporary file and reference that file in the `-d file:/my/tmp/http-dependency.jar`.
