### ISSUE TITLE
CLI parameter does not overwrite application.properties

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#2538]
Some Camel-K integration uses a modeline to define a property file like this
```
// camel-k: language=java property=file:application.properties
```

Properties defined as CLI parameters on `kamel run` should be able to overwrite these properties

```
kamel run Foo.java -p foo.bar=something
```

So `foo.bar` property in application.properties should be overwritten. This is not working as expected with Camel-K 1.5.0.

**Comment by squakez** [comment]
I've analyzed it and it's not really a bug as the modeline just convert the configuration into a full `kamel run` command. The real problem is that we don't consider precedence of a single property over a file properties. I think that by including it we will also fix the problem described in this issue.
