### ISSUE TITLE
Camel 3.15 - Data formats renamed

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#2880]
See ticket
https://github.com/apache/camel-quarkus/issues/3460

This means that the algorithm in camel-k that detects camel components (in this case data formats) may need to be changed due to the renamed names.

**Comment by davsclaus** [comment]
The camel-k catalog needs to be updated / rebuild as it uses the old names - eg if you do a 

git grep "jacksonxml"
git grep "mime-multipart"

**Comment by astefanutti** [comment]
Is the list from https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_15.adoc#data-formats exhaustive, or these are examples?

I'm asking because there are a number of kebab-cased references in the current CamelCatalog resource based on Camel 3.12.0, like `json-jackson`, `protobuf-jackson`, `avro-jackson`, `json-johnzon`, `json-jsonb`, `mime-multipart`, `yaml-snakeyaml`, ... that are not in that list. That being said, I expect the name changes to be picked up automatically once we regenerate the CamelCatalog. But there is some hard-coding for `json-jackson` and the `marshal` DSL to JSON.

**Comment by squakez** [comment]
Ref #3213

**Comment by tadayosi** [comment]
I assume it's already done, so let me close it. Please reopen if I'm wrong.
