### ISSUE TITLE
kustomize: generate namespaced and descoped rbacs

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3165]
As today, a number of rbac can be found in the [repo](https://github.com/apache/camel-k/tree/main/config/rbac)  but when the operator should be installed in cluster mode, then all those rbca have to be translated from namespace to cluster (Role to ClusterRole, RoleBinding to ClòusterRoleBiding) which is of course possible but not very easy.

I wonder if we can generate them by default instead of having to use kustomize to transform them, i.e. we can add two additional folders:

- config/rbac/namespaced
- config/rbac/descoped

**Comment by squakez** [comment]
cc @phantomjinx

**Comment by gansheer** [comment]
@lburgazzoli Do you mean having both version as files in the repo instead of generating "clustered" versions ?

**Comment by phantomjinx** [comment]
> @lburgazzoli Do you mean having both version as files in the repo instead of generating "clustered" versions ?

@gansheer I would say, yes, that is what @lburgazzoli means. There are advantages to it in that you don't then need to use the `Makefile` in order to leverage a `kustomize` cluster version install. 

This is balanced by the usual disadvantage that more files are present in the repo and so have to be maintained. However, in this case I don't think this is a real problem.

**Comment by lburgazzoli** [comment]
@gansheer yes correct, the main goal is to provide a simple `kubectl apply -k https://github.com/apache/camel-k//config/global` option to install camel-k

**Comment by gansheer** [comment]
That fits the work I am doing refactoring kustomize.
@squakez I will work on this.

**Comment by gansheer** [comment]
Yes, I am closing it.
