### ISSUE TITLE
E2E repeated failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3315]
I've notices some repeated test failure because of:
```
Unable to retrieve the operator version: no matches for kind "IntegrationPlatform" in version "camel.apache.org/v1"
Error: the server could not find the requested resource (get integrationplatforms.camel.apache.org)
```
Apparently, when we delete the resource *after* the tests are completed, we sometimes are not able to delete the IntegrationPlatform. We should figure out why and avoid the test to fail for such reason.

**Comment by squakez** [comment]
fyi @tadayosi

**Comment by tadayosi** [comment]
Where do you find this?  I looked at the upgrade testing for `release-1.9.x` branch but it seems to be failing with the same error.
https://github.com/apache/camel-k/runs/6647282436?check_suite_focus=true
```
=== RUN   TestOLMAutomaticUpgrade
    olm_upgrade_test.go:64: Testing cross-OLM channel upgrade stable-1.9 -> stable-dev-1.9
Using external kamel binary on path /tmp/kamel-1.9.1
OLM is available in the cluster
Error: exit status 2
Usage:
   [flags]

Flags:
  -h, --help   help for this command

    olm_upgrade_test.go:80: 
        Expected success, but got an error:
            <*exec.ExitError | 0xc00079b320>: {
                ProcessState: {
                    pid: 50946,
                    status: 512,
                    rusage: {
                        Utime: {Sec: 0, Usec: 240206},
                        Stime: {Sec: 0, Usec: 36641},
                        Maxrss: 67340,
                        Ixrss: 0,
                        Idrss: 0,
                        Isrss: 0,
                        Minflt: 4642,
                        Majflt: 30,
                        Nswap: 0,
                        Inblock: 4768,
                        Oublock: 0,
                        Msgsnd: 0,
                        Msgrcv: 0,
                        Nsignals: 0,
                        Nvcsw: 1099,
                        Nivcsw: 659,
                    },
                },
                Stderr: nil,
            }
            exit status 2
    dump.go:44: -------------------- start dumping namespace test-65e61bbb-89ec-43e5-90bd-4fc693ebd592 --------------------
    test_support.go:1752: Error while dumping namespace test-65e61bbb-89ec-43e5-90bd-4fc693ebd592: the server could not find the requested resource (get integrationplatforms.camel.apache.org)
--- FAIL: TestOLMAutomaticUpgrade (39.77s)
```

Note the last log line just comes from `test_support.go` where it tries to run the final clean up of the test, which I think just fails because the main part of the test has failed and there's no resource to clean up.

**Comment by squakez** [comment]
It's in the latest merge of `main` branch (https://github.com/apache/camel-k/runs/6647187769?check_suite_focus=true). I've also seen it in other PR on main as well.

**Comment by tadayosi** [comment]
Ah I see. It looks like a false alarm as well, which is coming from the clean up script. For the current `main` branch, it seems the problem is in the CI script itself.
```
make: 0.0: Command not found
make: *** [Makefile:530: bundle] Error 127
Error: Process completed with exit code 2.
Error: Unable to process file command 'env' successfully.
Error: Invalid environment variable format '0.0'
```
This error makes me feel that somewhere in the script there is code that tries to process the revision from `1.10.0` and fails to extract, which used to be `1.9.n` and thus worked. I'll see if I can fix it quickly.

**Comment by tadayosi** [comment]
The root cause is that this Makefile variable has to be a single-line string but is actually multi lines:
```
BUNDLE_METADATA_OPTS=--channels=stable-dev-1.1
0.0 --default-channel=stable-dev-1.1
0.0 --package=camel-k
```
This makes `make bundle` fail on CI.
