### ISSUE TITLE
Native E2E tests failing

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3715]
I see native e2e tests failing throughout branches and PRs

https://github.com/apache/camel-k/actions/workflows/install.yml 

From what I see in the logs the native build used in the e2e test is stuck in phase build running and the test finally hits validation timeouts (currently 10 mins). Maybe 3/10 times this tests is failing with timeouts. We need to investigate and see if this happens due to slow CI environment or how to improve the native e2e tests.

**Comment by squakez** [comment]
I remind some work on timeout was done by @tadayosi

**Comment by tadayosi** [comment]
Yes, if we are talking about this failure, I know why it sometimes happens.
```
📦 github.com/apache/camel-k/e2e/namespace/native
❌ TestNativeIntegrations (32m57.36s)
❌ TestNativeIntegrations/automatic_rollout_deployment_from_fast-jar_to_native_kit (30m54.21s)
✅ TestNativeIntegrations/unsupported_integration_source_language (1.03s)
✅ TestNativeIntegrations/warm_up_before_native_build_testing (1m41.61s)
```
The problem is that since Quarkus 2.11.3 a native build requires more memory whereas GitHub Actions only provide 7GB for the `ubuntu` GitHub runner. I tried to find the balance between successful build and avoiding OOME on the container and this was the result:
https://github.com/apache/camel-k/blob/main/e2e/namespace/native/native_test.go#L45-L49
Actually, recommendation for `-Dquarkus.native.native-image-xmx` is much higher in general, such as >=6g or even >=8g. And it's quite possible that upgrading to Quarkus 2.13.0 it becomes severer and the rate of success gets down further.

So ultimately unless GitHub gives us more memory for a GitHub runner in the future the problem won't be solved. Or we'd need to find a way to use a self-hosted runner for the upstream project. Or it's just a thought experiment, but GitHub-hosted `macos` runners have 14GB so running the native build e2e tests on a `macos` runner might possibly solve it?
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by tadayosi** [comment]
As a simple workaround I just increased the build timeout from 30 to 40 mins with PR #3747:
```
📦 github.com/apache/camel-k/e2e/namespace/native
✅ TestNativeBinding (33m55.87s)
✅ TestNativeBinding/kamelet_binding_with_native_build (32m3.04s)
✅ TestNativeBinding/warm_up_before_native_build_testing (1m38.2s)
✅ TestNativeIntegrations (34m14.21s)
✅ TestNativeIntegrations/automatic_rollout_deployment_from_fast-jar_to_native_kit (32m24.14s)
✅ TestNativeIntegrations/unsupported_integration_source_language (1.05s)
✅ TestNativeIntegrations/warm_up_before_native_build_testing (1m34.08s)
```
So apparently native builds take 28~35 mins on GitHub workflows. At this moment, probably relaxing the timeout is the only way we can do to mitigate the problem.
