### ISSUE TITLE
Kamelet API test rate limit

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3760]
```
--- FAIL: TestNewRepositoryWithCamelKamelets (0.06s)
    repository_test.go:151: 
        	Error Trace:	repository_test.go:151
        	Error:      	Received unexpected error:
        	            	GET https://api.github.com/repos/apache/camel-kamelets/contents/kamelets: 403 API rate limit exceeded for 20.230.23.20. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 50m05s]
        	Test:       	TestNewRepositoryWithCamelKamelets
    repository_test.go:152: 
        	Error Trace:	repository_test.go:152
        	Error:      	Should be true
        	Test:       	TestNewRepositoryWithCamelKamelets
```
I think we need to review that test to mitigate the number of API hit.

**Comment by tadayosi** [comment]
Probably the issue is not only for testing, but rather more broadly related to the way how the cli and testing interact with GitHub API.
https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps

So a cli which interacts with GitHub API should be aware of `GITHUB_TOKEN` and when it's available it should use the token to mitigate the rate limits. For example, we interact with GitHub API through `kamel run` and when we run `kamel run github:...`  many times we'll hit the same rate limit issue.

Likewise GitHub Actions provides a `secret.GITHUB_TOKEN` for each workflow so we can utilise the token for the CI tests.

**Comment by squakez** [comment]
Marking as a bug as this is starting to fail with insistence in our checks. Should be solved with priority.
