### ISSUE TITLE
Create normal service when knative-service trait is disabled

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3849]
Camel K automatically creates Knative services for integrations when Knative serving is available on the cluster. This is done in the knative-service trait. 

In case for some reason knative-service trait is disabled (either globally on the cluster or explicitly on the integration) Camel K should fallback to a normal service. At the moment when knative-service trait is disabled but Knative serving is available on the cluster no service at all is created.

**Comment by tadayosi** [comment]
It's related to how the profile is detected for an integration. Whenever you have Knative serving in the cluster, integrations are by default resolved to `Knative` profile. And Service trait is enabled only when the profile is either `Kubernetes` or `OpenShift`.

You should be able to fix the issue by explicitly assign one of them for an integration instead of letting it unspecified in an env where Knative serving is installed already.

So I think the questions are two-fold:

1. Does it make sense to disable Knative Service trait under `Knatvie` profile?  And does it make sense to create a service when the profile is `Knative`?
2. Should we improve the current profile detection logic?  If yes, how?
    https://github.com/apache/camel-k/blob/v1.10.3/pkg/controller/integration/platform_setup.go#L68-L89

**Comment by tadayosi** [comment]
cc @claudio4j

**Comment by christophd** [comment]
Setting the profile for an integration may not be what we want. A different profile may disable the whole Knative feature portfolio and we only need to disable the knative-service feature. Maybe we want to keep knative eventing and ksink injection but only disable knative-service trait for some reason.

I think the profile detection is fine as it is. but we need to have a decent fallback when a specific trait gets disabled for some reason. At the moment we do not create a service at all which is not good. we need to fallback to a normal service when knative-service gets disabled.

**Comment by claudio4j** [comment]
My understanding is the profile helps driving the traits and other logic in camel-k-operator, but there may be issues related to competing traits, and this knative-service/service is one of them, mutually exclusive traits. Christoph's comment is also right.

**Comment by christophd** [comment]
@claudio4j I think this one has already been fixed, right?

**Comment by squakez** [comment]
It seems so, closing.
