### ISSUE TITLE
Cannot retrieve Camel K operator version when in global mode in different ns

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#3854]
When Camel K Operator is installed in global mode, and if the kubectl current namespace is different than the ns the camel-k-operator is installed, then running `kamel version -a` results is misleading.
```
$ kamel version -a
No IntegrationPlatform resource in default namespace
Camel K Client Red Hat 1.10.2

Unable to retrieve operator version: integrationplatforms.camel.apache.org "camel-k" not found
```

kamel should be able to detect the camel-k-operator in the other ns to report correctly.

**Comment by squakez** [comment]
This was the original design. As we're moving more into a multi tenancy operator model it may makes sense to list all the operators available and their related names. However, this may be challenging because the `IntegrationPlatform` may not be always present and we should make sure that the `IntegrationPlatform` we're looking for is the one reconciled by the given operator.
