### ISSUE TITLE
how to set body of OUT message in yaml DSL?

### ISSUE THREAD

**Issue by wuyexixi** [apache/camel-k#4144]
like this java DSL do?

exchange.getOut().setBody("Message received);

**Comment by wuyexixi** [comment]
This example is set the IN message's body. I want to set the OUT message body without any headers from IN message. etc.

**Comment by gansheer** [comment]
I think the answer is actually the one that @squakez gave you but you need to use the `- set-body` in the right place in your route to be able to access the response body instead of the request body.

As for the headers from the IN message, if you want to remove them you need to use the [remove headers component](https://camel.apache.org/components/next/eips/removeHeaders-eip.html)
```yaml
      - removeHeaders:
          pattern: "*"
```


You can ask more help on the user mailing list or the zulip chat room. Your question is more general Camel YAML DSL questions than Camel K specific.

https://camel.apache.org/community/support/
