### ISSUE TITLE
Kamel run sample integration is failing to run

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4150]
I have created a java code as mentioned below 

<img width="472" alt="Screenshot 2023-03-22 174852" src="https://user-images.githubusercontent.com/128601152/226903141-20dc4529-0c31-4ac8-82f0-bc82d79a8ea6.png">

I have followed below process (here Iam using kubernetes inside docker not minikube)
<img width="475" alt="image" src="https://user-images.githubusercontent.com/128601152/226903648-ffb3f4e6-f080-4bc4-a3be-2e21b6accb1b.png">

after mentioned steps i tried to run a simple java program but it is failing, it is tried to build 5 times but every time it is failed.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/128601152/226904222-d780fdd1-f338-4d4f-b5ff-cb8f86faa408.png">

**Comment by chander35** [comment]
I tried with removing @Component annotation but no use, it is not working, the build failed again. it was working fine before but not now, i tried in many ways but not able to figure out what's wrong.

**Comment by heiko-braun** [comment]
Did you remove the import statement too?

**Comment by gansheer** [comment]
I would suggest you try to get more infos inside your kubernetes cluster directly:
* Check the logs of your operator with `kubectl logs camel-k-operator-xxxxx` and see if you have any errors
* Check the events of the pod with `kubectl describe pod camel-k-operator-xxxxx`
* Check the presence of the camel custom resources with:
  * `kubectl get integrations.camel.apache.org` : this is your integration
  * `kubectl get builds.camel.apache.org`: this is the build that should have been launched for your integration
  * `kubectl get integrationkits.camel.apache.org`: this is the integration kit resource that correspond to the container image that will be used to run the integration
* Check each one that is not in the right state with `-o yaml` (like : `kubectl get integrations.camel.apache.org basic-new-application -o yaml`)

The informations of these CR should help you find where the problem is.

**Comment by chander35** [comment]
This is the error iam getting whenever i tried to build my java program.
<img width="762" alt="image" src="https://user-images.githubusercontent.com/128601152/227506410-af440e92-50b6-450a-944f-d0f9d0c56a32.png">

**Comment by squakez** [comment]
That is probably because the build is failing with some problem while parsing your Integration. Please, try with any of the examples provided in Camel K examples repository as a quickstart (ie, https://github.com/apache/camel-k-examples/blob/main/generic-examples/languages/Sample.java). If that is failing, it is likely that your installation procedure was missing some step. See all the details as reported in official documentation: https://camel.apache.org/camel-k/next/installation/installation.html

**Comment by essobedo** [comment]
I see several potential problems:

1. As your class is called `Basic`, the name of the file should rather be `Basic.java`
2. The annotation `@Component` should be removed
3. The import `org.apache.camel.builder.RouteBuilder` is missing
4. Finally the configuration of the registry is incorrect, you are targeting the docker hub without credentials which is likely not intended. However, I believe that it is a good opportunity to describe the steps needed to install Camel-K when using Docker Desktop, I will propose a PR for that.

**Comment by essobedo** [comment]
Could you please try to follow [this guide](https://github.com/apache/camel-k/blob/a27b32a448b3d7b5a4bb740648121d43d19a6936/docs/modules/ROOT/pages/installation/platform/docker-desktop.adoc) to see if it helps?

**Comment by chander35** [comment]
the mentioned link-[: Add the installation guide for Docker Desktop](https://github.com/apache/camel-k/commit/a27b32a448b3d7b5a4bb740648121d43d19a6936) is helped to resolve the issue. thank you.
