### ISSUE TITLE
Bring in the option to have more verbose IntegrationKit names

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4205]
Creating this issue as per the discussion at [#4172](https://github.com/apache/camel-k/issues/4172).

[This](https://github.com/apache/camel-k/issues/4172#issuecomment-1486793595) pretty much summarizes my initial idea for this ticket.

Open to discussions.

**Comment by squakez** [comment]
It could be an idea. Right now, this is a kind of convention shared among `IntegrationKit` and `Build`, so, anything changed in one place may influence the other.

**Comment by lburgazzoli** [comment]
Please note that the integration kit is meant to be shareable among integrations and also survives the deletion of an integration so I would really try to avoid adding any prefix linked to the integration. If you want a kit per integration, then better to add an option to create a non shareable and garbage collectable kit (this happens already when you run an integration with a specific container image)

**Comment by squakez** [comment]
What probably makes sense for this feature is to introduce a field (or even an annotation) called `alias`. That one can be used by the final user to give a name to the Kit and it can be easily exposed by kube builder in CLIs.

**Comment by mertdotcc** [comment]
+1 for the `alias`.

**Comment by mertdotcc** [comment]
Another idea: instead of having kit names with alphanumeric/UUID-like suffixes (`kit-cge4mdsvri59ugp5v2hg` - `kit-cge5i2kvri59ugp5v2i0`), having them in simple version-like names. Example: `messaging-integration-kit-v1`, `booking-integration-kit-v4` etc.

What do you guys think?

**Comment by lburgazzoli** [comment]
For the reason in [this](https://github.com/apache/camel-k/issues/4205#issuecomment-1491456615) comment, I would really avoid using any integration name to name a context as it would be misleading.  An integration kit is meant to be independent from the integration it has been created from otherwise it would become useless.

**Comment by squakez** [comment]
Yes, as @lburgazzoli is mentioning, the idea of the Kits is to have them reusable. The name is something meaningful to the operator and should not be altered. That was the reason why I proposed the possibility to use an alias in order to easily identify the Kit but without altering the logic required by the operator.

**Comment by mertdotcc** [comment]
Okay, I see. Makes sense. Disregarded the fact that the kits are re-usable among different integrations. Then it's a super +1 from me for `alias`. 🙂
