### ISSUE TITLE
camel- k with spring cloud config

### ISSUE THREAD

**Issue by ajitghotane** [apache/camel-k#4370]
<img width="572" alt="image" src="https://github.com/apache/camel-k/assets/130899147/e258f0ec-b5d3-4e50-8eb3-5779a34107b2">

i am using this code to fetch config from spring cloud config server  and by using this command **kamel run Config.java --dev -d camel:core -d camel:camel-spring -d camel:spring-cloud** execute the code
<img width="547" alt="image" src="https://github.com/apache/camel-k/assets/130899147/5cc78b24-cf10-4c78-b9db-543333c54315">

but i am getting this error as mentioned above.

**Comment by gansheer** [comment]
I think your issue is related to the spring dependencies. Camel-k only support quarkus and tries to replace any camel-xxx dependency by [camel quarkus](https://camel.apache.org/camel-quarkus/3.0.x/reference/index.html) one declared in the CamelCatalog Custom Resource. You can go see your operator logs if you can get more informations `kubectl logs camel-k-operator-xxxxx`.

**Comment by squakez** [comment]
Yes, Camel K is actually only available with Camel Quarkus runtime (via Camel K runtime project). We are planning to extend [support on other runtimes in future Camel K versions](https://github.com/apache/camel-k/issues/4024), but not for the immediate future.
