### ISSUE TITLE
doesnt work "kamel kit delete" 

### ISSUE THREAD

**Issue by nuhyurduseven** [apache/camel-k#4628]
Hi, 
I can not delete camel kits via `kamel kit delete kit-<random_number>` command. Also `kamel kit delete --all` command doesn't work. I just use `kamel reset` to delete all kit. However, it's not an effective way. May kamel cli tool be problematic? How can I solve this issue? I am using latest `kamel` version and I am using minikube.

**Comment by gansheer** [comment]
Hi,

You probably can't delete the kit with the CLI command because it was created by the operator, so this is not a bug from the CLI. Therefore it is a platform one which is supposed to be "read only" thus not managed by the end user. This command is only available on user created integration kit.

You can delete it by removing the custom resource `kubectl delete integrationkit.camel.apache.org/kit-xxxxxxxxx` and also delete the container image in your registry. Be mindful that it is better to ensure any integration declaring it has been removed as well.

**Comment by squakez** [comment]
As @gansheer is pointing out, there is no "safe" way to delete an IntegrationKit because it could be used by any other Integration or as a base image for other IntegrationKits. In order to make sure that an IntegrationKit is safe to delete, you need to make sure it is not referenced by any other Integration or IntegrationKits.

**Comment by nuhyurduseven** [comment]
thanks @squakez . I deleted an image safely after control via `kamel describe kit kit-xxxxxxx` command. btw @gansheer's solution works, I deleted an image. But I notice that there are many images in `registry` service. When I use `minikube image ls`, I got many camel-k-kit,even deleted ones before. How  can I solve this problem? Why minikube remove images from registry?  
I used `kamel reset`, so all images, kits, integrations were gone. But I still see that the images are not removed like below.
`$ minikube image ls `
..... 
.....
.....
<registry service ip>//default/camel-k-kit-cj3qui2s8cu92eecfg3g:<none>
<registry service ip>/default/camel-k-kit-cj12rt2s8cu5l5ecufq0:<none>
<registry service ip>/default/camel-k-kit-cisdsnrtmpsjmj398i2g:<none>
<registry service ip>/default/camel-k-kit-cisdsajtmpsjmj398i20:<none>
...
....

**Comment by gansheer** [comment]
Interaction with any image registry from the camel-k CLI would be difficult because we would no longer be in the use case of a kubernetes API. 

On minikube the solution is to identify your kit images with something like `minikube image ls --format='table' | grep kit` and deleting them with `minikube image rm <image_id>`. As @squakez said, it could be scripted to check if the kit is still in use, but as you can see here we are using the `minikube` CLI which is specific to the registry you are using.

**Comment by nuhyurduseven** [comment]
OK. I deleted images with `minikube image rm`.  If I use kubernetes instead of minikube, can I delete a specific images via kamel ? Because I have to use organization registry when I use camel-k on kubernetes. In this case, I have to delete images with an automation script, right?  

Btw I got manifest errors sometimes  when the operator fetch an image and image building steps. I can't create a new integration with new image even if I run `kamel reset` command. This is not good for production environment? Why does it behave like this ?

**Comment by squakez** [comment]
Registry cleaning is some operation which has to be performed with the proper company privileges. I would not expect a production environment to let the operator to take care of such a sensitive operation. Remind that the registry images could be shared by other cluster as well, so, any delete operation must be done with particular care to avoid any later error when trying to run new Integrations.

**Comment by nuhyurduseven** [comment]
I got it. It makes sense. "kamel kit delete" feature is not require in this situation. Registry images and kits can be deleted in registry with `kubectl` command.
