### ISSUE TITLE
Support `kamel run ... -t camel.runtime-version=1.x` notation

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4739]
We already have the code in place to support semver and be able to get the best match accordingly. We need to verify what is exactly missing and provide the documentation with such a feature.

**Comment by claudio4j** [comment]
While working on #4715 I did some quick testing using the version scheme `2.16.x` and it will only match the camelcatalogs already installed in the namespace, for example given the camelcatalogs already added to the namespace:
```
camelcatalog/camel-catalog-1.17.0
camelcatalog/camel-catalog-2.16.1
camelcatalog/camel-catalog-2.16.5
```

If using `camel.runtime-version=1.17.x` or `camel.runtime-version=2.x`, the semver rule can match the mentioned camelcatalogs.

However if the user sets `camel.runtime-version=3.x` the semver check will fail and the next step is the camelcatalog controller code to generate the catalog, which will fail because the version `3.x` doesn't exist. In this case forcing the user to set an existing camelcatalog version `camel.runtime-version=3.0.0`

**Comment by squakez** [comment]
Yes, I think that the behavior should be to provide any matching catalog if exists, otherwise to fail (with a clear failing message) expecting the user to provide a fixed version.
