### ISSUE TITLE
Camel K offline error

### ISSUE THREAD

**Issue by liyongxian** [apache/camel-k#4894]
### What happened?

JDK:java version "17.0.9" 2023-10-17 LTS
maven: 3.8.8
![image](https://github.com/apache/camel-k/assets/18571576/e6d1fd5c-039c-41d9-a3ca-0d68974d98dd)

MAVEN BUILD  ERROR
![image](https://github.com/apache/camel-k/assets/18571576/af9ccaa5-336e-4ae9-b56e-43964ce880a7)

**Comment by squakez** [comment]
Thanks for reporting. The offline procedure is not something we officially support. As stated in the documentation, it's a best effort work. However, we can give a look to try to fix the script. It seems that the new quarkus catalog is providing certain dependencies which we don't expect [1]. Feel free to have a look and contribute. I think that, instead of exiting with an error we may download those dependencies as well the way they are.

[1] https://github.com/apache/camel-k/blob/e607cd0a560444ee93aaaef82ca6f3e53259229b/script/offline_dependencies.sh#L78
