### ISSUE TITLE
helm upgrade failing - empty task in build

### ISSUE THREAD

**Issue by hernanDatgDev** [apache/camel-k#4923]
### What happened?

After performing a `helm upgrade` of camel-k from version 2.0.0 > 2.1.0 the upgraded operator fails when building the integration kit image and as a result no integrations can be run. The error message from the upgraded operator when running a test integration is: "Build kit-clbu7f6l6e8c73f95f2g errored: **Cannot execute empty task in build** [default/kit-clbu7f6l6e8c73f95f2g]"

Both of these versions of camel-k work as expected when installed directly with helm (no upgrade). Interestingly, the IP is identical whether camel-k is installed with 2.1.0 or upgraded.

Relevant files:
* IntegrationPlatform.yaml (as text) before & after the helm upgrade.
* IntegrationPlatform.yaml (as text) after a `kamel` upgrade from version 2.0.0 > 2.1.0
[ip-original.txt](https://github.com/apache/camel-k/files/13417813/ip-original.txt)
[ip-upgraded.txt](https://github.com/apache/camel-k/files/13417814/ip-upgraded.txt)
[ip-upgraded-kamel.txt](https://github.com/apache/camel-k/files/13417830/ip-upgraded-kamel.txt)

### Steps to reproduce

1. Install camel-k 2.0.0 with helm
`helm install camel-k -f myValues.yaml camel-k/camel-k --version 2.0.0`
2. Upgrade to version 2.1.0 with helm
`helm upgrade -f myValues.yaml camel-k camel-k/camel-k --version 2.1.0 --force`
3. Attempt to successfully run any integration
`kamel run timer-log.groovy`

📓 NOTE: myValues.yaml only contains basic configurations for container registry & maven settings

### Relevant log output

```shell
{"level":"debug","ts":"2023-11-17T22:05:56Z","logger":"camel-k.builder","msg":"base image: eclipse-temurin:17"}
{"level":"debug","ts":"2023-11-17T22:05:56Z","logger":"camel-k.builder","msg":"resolved base image: eclipse-temurin:17"}
{"level":"info","ts":"2023-11-17T22:05:56Z","logger":"camel-k.controller.build","msg":"Build duration 8.182360494s","request-namespace":"default","request-name":"testing","build-attempt":0,"build-result":"Error","build-duration":8.182360494,"api-version":"camel.apache.org/v1","kind":"Build","ns":"default","name":"kit-clbu7f6l6e8c73f95f2g"}
{"level":"error","ts":"2023-11-17T22:05:56Z","logger":"camel-k.controller.build","msg":"Build kit-clbu7f6l6e8c73f95f2g errored: Cannot execute empty task in build [default/kit-clbu7f6l6e8c73f95f2g]","request-namespace":"default","request-name":"kit-clbu7f6l6e8c73f95f2g","api-version":"camel.apache.org/v1","kind":"Build","ns":"default","name":"kit-clbu7f6l6e8c73f95f2g","stacktrace":"github.com/apache/camel-k/v2/pkg/util/log.Logger.Errorf\n\tgithub.com/apache/camel-k/v2/pkg/util/log/log.go:60\ngithub.com/apache/camel-k/v2/pkg/controller/build.(*monitorRoutineAction).updateBuildStatus\n\tgithub.com/apache/camel-k/v2/pkg/controller/build/monitor_routine.go:218\ngithub.com/apache/camel-k/v2/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/v2/pkg/controller/build/monitor_routine.go:200"}
{"level":"debug","ts":"2023-11-17T22:05:56Z","logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"default","request-name":"kit-clbu7f6l6e8c73f95f2g"}
```

### Camel K version

2.0.0 & 2.1.0

**Comment by squakez** [comment]
@gansheer I've seen in zulip chat you have already managed to reproduce it. Are you going to work on this?

**Comment by gansheer** [comment]
Yes, I will.

**Comment by gansheer** [comment]
This error is due to the `helm upgrade` command not updating the CRDs (Custome Resource Definitions).

You should see in your integrationkit Custom Resource that it contains in `.spec.task` a `{}` where the new `package` task should be:
```yaml
...
spec:
  tasks:
  - builder:
...
  - {}
  - spectrum:
...
```
(the last task could be any other publish strategy name)


The fact that the `helm upgrade` command does not update the CRDs is a [design choice](https://github.com/helm/helm/issues/7735) from Helm so there is no bug on their side.

For now I suggest you use the workaround of manually updating the CRDs in your procedure (this example use kustomize):

1. Install camel-k 2.0.0 with helm
`helm install camel-k -f myValues.yaml camel-k/camel-k --version 2.0.0`

2. Update the CRDs to the target version:
`kubectl apply -k "https://github.com/apache/camel-k/main/helm/camel-k/crds?ref=v2.1.0"`

3. Upgrade to version 2.1.0 with helm
`helm upgrade -f myValues.yaml camel-k camel-k/camel-k --version 2.1.0 --force`

**Comment by squakez** [comment]
https://github.com/apache/camel-k/blob/main/release.adoc#helm - I presume Helm picks the readme from the doc charts. We need to backport if we plane to release 2.1.1.

**Comment by oscerd** [comment]
Yes, backport is needed

**Comment by gansheer** [comment]
The fix is an update on the helm documentation. From what I could read there is no change to be made on our side as the CRDs are a special case in helm. Helm allows for them to be installed with the initial installation of them, but the CRDs will not be changed in any upgrade. 

In short, before an helm upgrade the CRDs need to be upgraded to the target version before (https://github.com/apache/camel-k/pull/4927/files#diff-5ecd878fd0342b8721fbb49a789bfdd2f597c69c0024f8759f668f5fa10a327e).

The documentation will be updated for the next 2.2, 2.1.x and 2.0.x releases.

**Comment by gansheer** [comment]
@squakez this can be closed.
