### ISSUE TITLE
Usage of older Kameletes version on main

### ISSUE THREAD

**Issue by matzew** [apache/camel-k#4985]
### Requirement

Make latest data-types (for Azure Storage Blob (and others)) avainable

### Problem

Looking here: https://github.com/apache/camel-k/blob/main/script/Makefile#L89

I see usage of `4.0.0`, but there are already newer versions, like `4.1.0` or `4.2.0`.

In https://github.com/apache/camel-kamelets/issues/1777 it was discussed that this needs to be updated,

as well as using a camel-quarkus, that points to 4.2.0.

But as of Nov there is a 3.6.0 of camel-quarkus
https://mvnrepository.com/artifact/org.apache.camel.quarkus/camel-quarkus-core/3.6.0

**Comment by squakez** [comment]
This is correct. The "default" kamelet bundle used is the one belonging to the default Camel version. As soon as we move to Camel 4.2 (likely next week), we will update accordingly. However, mind that since Camel K can run other runtime versions, you need to make sure the Kamelet specification is in line with the runtime used [1].

[1] https://camel.apache.org/camel-k/next/kamelets/kamelets-distribution.html
