### ISSUE TITLE
Consistent Labelling

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#505]
Can all the k8s objects created or belong to camel-k have consistent labelling? e.g the services/deployment deployed by camel-k have a label like `app=camel-k`

**Comment by jacobborella** [comment]
I looked at this bug. Can't find any inconsistencies. Only in the file deploy/cr-example.yaml, which isn't used anywhere.

What is your opinion on unreferenced code. Should it be removed?

**Comment by Deepthi562** [comment]
can it be assigned to me?

**Comment by squakez** [comment]
All operator resources are already labelled as `app=camel-k`. Any Integration can be labeled with `kamel run --label` parameter, possibly in conjunction with `owner.target-labels` [1] in order to transfer labels to resources created by such an Integration. 

[1] https://camel.apache.org/camel-k/next/traits/owner.html
