### ISSUE TITLE
Error with Knative probes

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#528]
I've tested health checks (#511) in Knative 0.3 on minishift and I get an error from the admission webhook. Are they supported? Since which version?

(used the knative example, printer service)

@kameshsampath , @lburgazzoli

**Comment by kameshsampath** [comment]
what kind of errors ? I guess i have been using the v0.3. for long time and I dont get any errors.. sometimes I see random errors because of sleep/awake of macOS. Also I would feel that we need to make minikube as upstream standard as Knative will never get into support for v3.x of OpenShift and v4 of OpenShift might not have minishift

**Comment by lburgazzoli** [comment]
I think it is related to this:

    https://github.com/knative/serving/blob/master/docs/runtime-contract.md#meta-requests

We need to apply a different rule for knative
