### ISSUE TITLE
TestHelmOperatorUpgrade error

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5304]
❌ TestHelmOperatorUpgrade (6m10.33s)
      helm_upgrade_test.go:152: 
          Timed out after 300.000s.
          Expected
              <v1.PodPhase>: 
          to equal
              <v1.PodPhase>: Running

**Comment by squakez** [comment]
The test is wrong as it does not rebuild an Integration, but it creates it from scratch. I tried to amend it in #5305 but it's failing because we are deleting CRDs: https://github.com/apache/camel-k/blob/fe99b4c47befb6575cf47bd47a3d2d473c82ae9d/e2e/install/upgrade/helm_upgrade_test.go#L102-L112 

This is bringing to the situation that the original Integration is deleted together with the removal of CRDs. We need to rework this test or remove it at all as it does not reflect any real production procedure we're suggesting when upgrading within Helm framework.

**Comment by christophd** [comment]
I recall that this tests has had issues with new CRDs that have been added to the codebase but not yet released. The situation was that the helm upgrade wanted to replace a CRD that does not exist (the new one)

I think deleting the CRDs fixed this situation as the helm upgrade will create instead of replace. But I am not 100% sure
