### ISSUE TITLE
Contributing page is obsolete

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5386]
See https://camel.apache.org/camel-k/2.3.x/contributing/developers.html

We should provide up to date information.

**Comment by vkrejcirik** [comment]
I will look into this one as my first contribution to the project. Can you assigned this issue to me?

**Comment by squakez** [comment]
Great, thanks! Feel free to contact for any required support.

**Comment by vkrejcirik** [comment]
@squakez I followed instruction in [Contributing to Camel K](https://camel.apache.org/camel-k/2.3.x/contributing/developers.html) and I faced an issue when running `make lint`.  The Makefile is using `golangci-lint` with parameter `--deadline`, but it seems like this is not valid parameter anymore. At least in the most recent version - 1.57.2.

**Comment by squakez** [comment]
Yes, I think we're actually using `1.55.2` version. Probably it is worth to mention this in the instructions to verify which is the actual version we are using. Also mind that the part mentioning `pre-commit install` is something that may not work either and it could be removed from the guide.

**Comment by vkrejcirik** [comment]
I downgraded to version `v1.55.2` and it worked just fine. I added specific version into instruction. I removed `pre-commit` option from the page. I'm not able to verify the Windows specific instructions since I'm running on MacOS. So, hopefully that's okay. I was able to build the complete project just fine as well as Camel K operator image.
