### ISSUE TITLE
Install on Kind with local registry lacks info about helm chart on a kind cluster with local repo

### ISSUE THREAD

**Issue by matzew** [apache/camel-k#5651]
### Requirement

In here https://github.com/apache/camel-k/blob/main/docs/modules/ROOT/pages/installation/platform/kind.adoc

it would be nice if shown how to `helm install` on kind, with a local registry.

### Problem

Unclear how to 
```
helm install \
  --generate-name \
  --set platform.build.registry.address=${REGISTRY_ADDRESS} \
  --set platform.build.registry.insecure=true \
  camel-k/camel-k
```

w/ kind (and local registry)

### Proposal

add instructions for that

**Comment by squakez** [comment]
Running a local registry on Kind is a bit hacky (see https://camel.apache.org/camel-k/2.3.x/installation/registry/own.html#configuring-registry-run-docker). This is the reason why there is no "official" documentation around that.

**Comment by matzew** [comment]
The documentaton there seems to be for minikube (at least the text implies that), and in kube there is actually a pod.

For `kind` it works like this: https://kind.sigs.k8s.io/docs/user/local-registry/

and the doc there states, that you can use it as `kind-registry:5000` inside the cluster.

However using that, I am getting:

```
camel-k-operator-59c546df55-zb57n camel-k-operator {"level":"info","ts":"2024-06-18T10:18:43Z","logger":"camel-k.controller.integration","msg":"Integration error","request-namespace":"default","request-name":"beer-source-pipe","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"beer-source-pipe","reason":"Error","error-message":"Back-off pulling image \"kind-registry:5000/default/camel-k-kit-cpolsiek39ld6n7ftug0@sha256:00ca681c11c1a1a66d01c1cbd93a020d45b1397af37e5c7938be2b4f6e046e86\""}
```

**NOTE:** I am with podman

**Comment by christophd** [comment]
yes, you can reference the registry with `kind-registry:5000`.

I am also running on Podman and I had to tell Camel K that this is an insecure registry otherwise I had same image pull backoff errors. I am doing the install with `kamel install` though adding the `--registry-insecure` option. This has done the trick for me with Camel K running on Kind and Podman.

**Comment by christophd** [comment]
See https://camel.apache.org/camel-k/2.3.x/installation/platform/kind.html for more details and the `kamel install` command at the very end of the article

**Comment by matzew** [comment]
Thanks @christophd I'd like to actually not use the `kamel` CLI, just helm, like:

```
helm install \
  --generate-name \
  --set platform.build.registry.address=http://kind-registry:5000 \
  --set platform.build.registry.insecure=true \
  camel-k/camel-k
```

But using that, I am getting the above discussed `Back-off pulling image ` error on the Operator when I am applying a `Pipe` manifest

**Comment by squakez** [comment]
`--set platform.build.registry.address=http://kind-registry:5000` is maybe `--set platform.build.registry.address=kind-registry:5000`

**Comment by christophd** [comment]
@matzew sorry, I have overlooked that you already set insecure registry with `--set platform.build.registry.insecure=true`

for sure there is some piece missing with Helm installation on Kind with Podman because I am successfully using the same setup. The only difference I see is that I am installing with kamel CLI instead of Helm. Have you had success with this type kamel CLI type of installation already? just to be sure that it is a missing piece of Helm based Camel K install.

I think the pull back-off is not limited to Pipes is it? Maybe you can verify some other integration. It should be failing, too.

**Comment by christophd** [comment]
BTW I have had similar pull image back-off errors earlier on Minikube with Podman because the container-runtime `cri-o` kept using `https` to access the registry regardless of setting `insecure=true` for the registry. I could not resolve this for Minikube so I have switched to Kind cluster where it is working as expected with Podman
