### ISSUE TITLE
Integrations built with build strategy Spectrum do not start

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5759]
### What happened?

After creating an Integration that uses Spectrum, the Integration pod fails to start with the error:
```
Error: Could not find or load main class io.quarkus.bootstrap.runner.QuarkusEntryPoint
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.runner.QuarkusEntryPoint
```
Inspecting the Integration image I see that all files are owned by root. This seems to be a similar case to https://github.com/apache/camel-k/issues/4955.

I know that Spectrum is deprecated and I'm using Jib, but my goal here is to check If I'm able to reproduce https://github.com/apache/camel-k/issues/5758 with Spectrum as well. 

### Camel K version

2.4.0

**Comment by squakez** [comment]
Yeah, I think it is the same privilege problem like it happened with other strategies. Since version 2.4 we've limited the privileges for containers by default. However you can use the ["Security Context" trait](https://camel.apache.org/camel-k/2.4.x/traits/security-context.html) and run this with root privileges to see if that is enough for the Spectrum to run. As you said, we're probably dropping support for Spectrum already in 2.5.0.

**Comment by lsergio** [comment]
Now that we understand what #5758 is about, we can close this, as Spectrum is deprecated.
