### ISSUE TITLE
Integration naming issues with numbers in them

### ISSUE THREAD

**Issue by utherp0** [apache/camel-k#777]
If you create integrations with the same name but ending in a number the number is ignored and identical integrations are created linked to the *same* deployed Pod.

For example:

~/camelk/kamel run Sample.java --name=looknoeap1

Results in a deployment occurring with the name 'looknoeap'. If I then do:

~/camelk/kamel run Sample.java --name=looknoeap2

I get - integration "looknoeap" updated

For some reason the naming convention is dropping numbers at the end - it also ignores '-', i.e. --name=looknoeap-2 resolves to 'looknoeap' as well.

However, if I then do:

~/camelk/kamel run Sample.java --name=looknoeap-two

It creates an integration called 'looknoeap-two.

**Comment by jamesnetherton** [comment]
It's because of [this](https://github.com/apache/camel-k/blob/master/pkg/util/kubernetes/sanitize.go#L38) that any non letter characters are trimmed from the start & end of the name.

I think this is a bit too strict. IIRC Pod, Deployment & Container names validate to the DNS naming rules outlined in RFC 1123. So starting or ending the name with a numeric value should be allowed.

**Comment by utherp0** [comment]
Yup, agreed - I only found it because I have a tendency to use xxxxy for demos and noticed that one integration was created and every other test I did updated that one :-)
