### ISSUE TITLE
Camel-K operator should clean up kits and kit builders after integrations are deleted

### ISSUE THREAD

**Issue by bfitzpat** [apache/camel-k#889]
Now that adding a new integration creates a `camel-k-kit-*` and `camel-k-kit-*-builder` along with the integration pod itself, it seems there should be some clean up to remove those when the integration is deleted? I'm seeing the custom resource/integrationkits still hanging around after I remove the integrations.

**Comment by bfitzpat** [comment]
Running `kamel reset` does help clean up the errant artifacts, so that's a good workaround in the short term.

**Comment by lburgazzoli** [comment]
It should certainly clean-up builder but kits need to be kept as they are needed to properly determine how and if new container images have to be built

**Comment by dhirajsb** [comment]
There seems to be an underlying assumption that the user will run the same integration again and hence the kit needs to be kept around. 

Doesn't that lead to the following:
* Deleting an integration completely is a two step process, delete the integration then deleting the kit separately. 
* If a user deletes an integration without knowing that kit has to be deleted separately, kits will start piling up in the background, since `kamel get` only lists integrations. 

I think the integration lifecycle is kinda ambiguous, since running an integration both builds,  deploys and runs it, and there is no clean state transition to deleting an integration completely. 

At a higher level, there is a disconnect from when an integration comes into existence (preferably in a vcs), to being run using `kamel`.

**Comment by lburgazzoli** [comment]
> There seems to be an underlying assumption that the user will run the same integration again and hence the kit needs to be kept around.
> 

An integration kit is by design not tight to a specific integration but can be reused by any other integration that requires the same set of dependencies or it can be used as base image for a subsequent build to reduce the amount of data transferred from/to the registry, that's why kits are not deleted along with integrations.

**Comment by astefanutti** [comment]
One approach would be to implement a GC-like mechanism that would run periodically and remove the unreferenced kits, created since longer than a configurable period of time. Otherwise, we can add a `prune`-like operation to the Kamel CLI that would ease removing the kits.

**Comment by lburgazzoli** [comment]
There's actually a quire old issue: https://github.com/apache/camel-k/issues/254
