### ISSUE TITLE
Error after cluster restart

### ISSUE THREAD

**Issue by weimeilin79** [apache/camel-k#933]
Error appears when cluster restarts. 
CRD missing.

<img width="1405" alt="Screen Shot 2019-09-11 at 12 08 31 PM" src="https://user-images.githubusercontent.com/2534483/64727237-41bea080-d48d-11e9-9995-0ad92c7acbb3.png">

**Comment by nicolaferraro** [comment]
It's strange because objects being in state "Ready/Running" are almost not touched by the state machine, so at cluster startup they should not be changed. This is true especially for IntegrationKit and Build.

If the error is due to some CRD missing, then the operator should not be able to change the state of the CRs.

Do you have the operator logs to share?

**Comment by jamesnetherton** [comment]
This is maybe the same issue as #739? 

After restarting the cluster, any attempt to create or modify integrations results in:

```
{"level":"info","ts":1569938239.1303508,"logger":"camel-k.builder","msg":"step failed with error: cannot delete build config: no matches for kind \"BuildConfig\" in version \"build.openshift.io/v1\"","step":"github.com/apache/camel-k/pkg/builder/s2i/Publisher","phase":40,"kit":"kit-bm9llbs37plojukjjqjg"}
```

Restarting the operator fixes things.

**Comment by lburgazzoli** [comment]
@weimeilin79 is this still an issue ?

**Comment by weimeilin79** [comment]
Don't see it now.
